version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - setup_remote_docker:
         version: 17.05.0-ce
      - run:
          name: Build docker image
          command: docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$(echo $CIRCLE_BRANCH$CIRCLE_TAG | sed 's@/@-@') .
      - run:
          name: Install AWSCLI
          command: pip install awscli --upgrade --user
      - run:
          name: Login to AWS ECR
          command: $(PATH=~/.local/bin:$PATH bash -c "aws ecr get-login --no-include-email")
      - run:
          name: Push docker image to AWS ECR
          command: docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$(echo $CIRCLE_BRANCH$CIRCLE_TAG | sed 's@/@-@')
  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies to run upgrade rancher script
          command: pip install requests==2.18.4 baker==1.3 websocket-client==0.44.0 --upgrade --user
      - run:
          name: Run upgrade rancher script
          command: ./src/docker/rancher.py upgrade ${RANCHER_SERVICE_ID_PROD} --start_first=True --complete_previous=True --auto_complete=True --sidekickImageUuid=docker:$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$(echo $CIRCLE_BRANCH$CIRCLE_TAG | sed 's@/@-@')
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/