version: '2'
services:
  nginx:
     image: nginx:alpine
     network_mode: bridge
     links:
        - php
     environment:
        - VIRTUAL_HOST=yii2-boilerplate.docker
        - VIRTUAL_PORT=80
     volumes_from:
        - php
  php:
     build: .
     network_mode: bridge
     links:
        - db
     volumes:
        - /srv/www
        - ./src/www:/srv/www
     env_file: env
  db:
     image: mysql
     network_mode: bridge
     command: --max_allowed_packet=512M
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: yii2-boilerplate
#        MYSQL_USER: root
#        MYSQL_PASSWORD: root