version: '2'
services:
  nginx:
     image: nginx:alpine
     links:
        - php
     environment:
        - VIRTUAL_HOST=yii2-boilerplate.docker
        - VIRTUAL_PORT=80
     volumes:
        - vhost:/etc/nginx/conf.d:ro
     volumes_from:
        - php
  php:
     build: .
     links:
        - db
     volumes:
        - /srv/www
        - vhost:/runtime
        - ./src/www:/srv/www
     env_file: env
  db:
     image: mysql
     command: --max_allowed_packet=512M
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: yii2-boilerplate
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PASSWORD: root
volumes:
  vhost: