version: '2'
services:
  nginx:
     image: nginx:alpine
     links:
        - php
     environment:
        - VIRTUAL_HOST=yii2-boilerplate.docker
        - VIRTUAL_PORT=80
     volumes:
        - vhost:/etc/nginx/conf.d:ro
     volumes_from:
        - php
  php:
     build: .
     links:
        - db
     volumes:
        - /srv/www
        - vhost:/runtime
        - ./src/www:/srv/www
     environment:
        - DEFAULT_HOST=yii2-boilerplate.docker
        - ANPCONT_DOMAIN=yii2-boilerplate.docker
        - DB_HOST=db
        - DB_NAME=yii2-boilerplate
        - DB_USER=root
        - DB_PASS=root
        - YII_DEBUG=true
        - YII_ENV=dev
        - TERM=xterm
  db:
     image: mysql
     command: --max_allowed_packet=512M
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: yii2-boilerplate
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PASSWORD: root
volumes:
  vhost: